name: EpicParkour
version: '${project.version}'
main: me.bedrye.parkourgame.ParkourGame
api-version: '1.20'
authors: [ Bedrye ]
description: Parkour!
commands:
  ep:
    description: Main EP command
    usage: /<command>

permissions:
  epicParkourGame.*:
    description: Gives access to all commands
    default: op
